### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by luizaandrade** [dime-worldbank/pei-dashboard#5]
# Filters
- [x] country 
- [x] region (aggregate from country) -- list input
- [x] identification strategy
- [x] Priority population
- [x] PEI learning priority
- [x] PI affiliation

# Columns
- [x] Title
- [x] Research team? Not sure if this is possible, but would be good to have some sort of summary
- [x] Summary
- [x] Research questions
- [x] Geographic coverage
- [x] Area
- [x] Target method
- [x] Poverty segment
- [x] Priority population
- [x] Research questions

**Comment by ellenite** [comment]
The last four items are duplicated.

**Comment by luizaandrade** [comment]
- [ ] move title and summary as first two columns in the dashboard
- [ ] limit length of summary

**Comment by luizaandrade** [comment]
- [ ] Fix spacing in country column
