### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by luizaandrade** [dime-worldbank/pei-dashboard#6]
# Filter
- [x] identification strategy
- [x] PEI learning priority
- [x] PI affiliation

# Display
- [x] Select variable to be represented in the map
    - [x] Number of projects in the region
    - [x] Number of projects with a given priority group

**Comment by ellenite** [comment]
Added Priority Group as a filter instead of creating several variables based on the priority group.

**Comment by luizaandrade** [comment]
- [ ] Remove Antartica from map
- [ ] Remove NAs from Map label
- [ ] Remove map title
- [ ] Remove legend title
- [ ] Add pin for countries with active IEs (on centroid)
- [ ] Call projects "impact evaluations" not "programs"
- [ ] Do not display countries' frontiers
